// Package frr renders the IR's routing section into frr.conf. FRR runs
// as separate daemons; a marker line tells the engine supervisor which
// daemons the config needs (bgpd/ospfd) so it can manage the FRR
// daemons file.
package frr

import (
	"fmt"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// ModeMarker prefixes the mode line read by the engine supervisor.
const ModeMarker = "! openngfw-daemons: "

// ModeDisabled marks a config with no routing protocols enabled.
const ModeDisabled = "none"

// Render produces frr.conf.
func Render(ir *compiler.IR) ([]byte, error) {
	var b strings.Builder
	if ir.Routing == nil {
		b.WriteString(ModeMarker + ModeDisabled + "\n")
		return []byte(b.String()), nil
	}
	r := ir.Routing

	var daemons []string
	if r.BGP != nil {
		daemons = append(daemons, "bgpd")
	}
	if r.OSPF != nil {
		daemons = append(daemons, "ospfd")
	}
	b.WriteString(ModeMarker + strings.Join(daemons, ",") + "\n")
	b.WriteString("! Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n")
	b.WriteString("frr defaults traditional\n")
	b.WriteString("hostname openngfw\n")
	b.WriteString("!\n")

	if r.BGP != nil {
		fmt.Fprintf(&b, "router bgp %d\n", r.BGP.ASN)
		fmt.Fprintf(&b, " bgp router-id %s\n", r.BGP.RouterID)
		b.WriteString(" no bgp ebgp-requires-policy\n")
		for _, n := range r.BGP.Neighbors {
			fmt.Fprintf(&b, " neighbor %s remote-as %d\n", n.Address, n.RemoteASN)
			if n.Description != "" {
				fmt.Fprintf(&b, " neighbor %s description %s\n", n.Address, n.Description)
			}
		}
		if len(r.BGP.Announce) > 0 {
			b.WriteString(" address-family ipv4 unicast\n")
			for _, pfx := range r.BGP.Announce {
				fmt.Fprintf(&b, "  network %s\n", pfx)
			}
			b.WriteString(" exit-address-family\n")
		}
		b.WriteString("!\n")
	}

	if r.OSPF != nil {
		b.WriteString("router ospf\n")
		if r.OSPF.RouterID != "" {
			fmt.Fprintf(&b, " ospf router-id %s\n", r.OSPF.RouterID)
		}
		for _, area := range r.OSPF.Areas {
			for _, net := range area.Networks {
				fmt.Fprintf(&b, " network %s area %s\n", net, area.Area)
			}
		}
		b.WriteString("!\n")
	}

	return []byte(b.String()), nil
}
