// Package suricata renders the IR's IDS section into a suricata.yaml.
//
// The first lines carry an "openngfw-mode" marker the engine supervisor
// reads to decide whether to run Suricata and in which mode — the
// artifact stays a single self-describing blob.
package suricata

import (
	"fmt"
	"net/netip"
	"path/filepath"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// Options carries deployment paths that are not part of policy.
type Options struct {
	// RulesDir is the managed rule-file directory.
	RulesDir string
	// LogDir receives eve.json.
	LogDir string
}

// ModeMarker prefixes the mode line read by the engine supervisor.
const ModeMarker = "# openngfw-mode: "

// Mode strings used in the marker line.
const (
	ModeDisabled = "disabled"
	ModeDetect   = "detect"
	ModePrevent  = "prevent"
)

const (
	// ThresholdFileName is generated from OpenNGFW IDS exceptions.
	ThresholdFileName = "openngfw-threshold.config"
	thresholdBegin    = "# openngfw-threshold-begin"
	thresholdEnd      = "# openngfw-threshold-end"
	// ClassificationFileName avoids depending on host-global Suricata files.
	ClassificationFileName = "openngfw-classification.config"
	// ReferenceFileName avoids depending on host-global Suricata files.
	ReferenceFileName = "openngfw-reference.config"
	// AppIDRuleFileName is generated from signal-only App-ID deny rules.
	AppIDRuleFileName = "openngfw-appid.rules"
	appIDRulesBegin   = "# openngfw-appid-rules-begin"
	appIDRulesEnd     = "# openngfw-appid-rules-end"
	// SecurityProfileRuleFileName is generated from security profile controls.
	SecurityProfileRuleFileName = "openngfw-security-profiles.rules"
	securityProfileRulesBegin   = "# openngfw-security-profile-rules-begin"
	securityProfileRulesEnd     = "# openngfw-security-profile-rules-end"
)

// Render produces suricata.yaml. When IDS is disabled the artifact is
// only the disabled marker — the supervisor stops any running instance.
func Render(ir *compiler.IR, opts Options) ([]byte, error) {
	var b strings.Builder
	if ir.IDs == nil {
		b.WriteString(ModeMarker + ModeDisabled + "\n")
		return []byte(b.String()), nil
	}
	ids := ir.IDs

	mode := ModeDetect
	if ids.Prevent {
		mode = ModePrevent
	}

	queues := int(ids.QueueCount)
	if queues < 1 {
		queues = 1
	}

	b.WriteString("%YAML 1.1\n---\n")
	b.WriteString(ModeMarker + mode + "\n")
	if ids.Prevent {
		fmt.Fprintf(&b, "# openngfw-queue: %d\n", ids.QueueNum)
		fmt.Fprintf(&b, "# openngfw-queue-count: %d\n", queues)
	}
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n\n")

	// Run inspection across worker threads (one per NFQUEUE in prevent
	// mode, per capture thread in detect) and let the engine pick the
	// fastest pattern matchers (Hyperscan when the build provides it).
	b.WriteString("runmode: workers\n")
	b.WriteString("mpm-algo: auto\n")
	b.WriteString("spm-algo: auto\n\n")

	homeNets := make([]string, len(ids.HomeNets))
	for i, p := range ids.HomeNets {
		homeNets[i] = p.String()
	}
	b.WriteString("vars:\n  address-groups:\n")
	fmt.Fprintf(&b, "    HOME_NET: \"[%s]\"\n", strings.Join(homeNets, ","))
	b.WriteString("    EXTERNAL_NET: \"!$HOME_NET\"\n\n")

	fmt.Fprintf(&b, "default-log-dir: %s\n", opts.LogDir)
	// Capture size follows the managed MTU so jumbo frames are not
	// truncated in detect mode (+18 covers the Ethernet header).
	if ir.Network != nil && ir.Network.MaxMTU > 0 {
		fmt.Fprintf(&b, "default-packet-size: %d\n", ir.Network.MaxMTU+18)
	}
	b.WriteString("\n")

	b.WriteString("stats:\n  enabled: no\n\n")

	b.WriteString("outputs:\n")
	b.WriteString("  - eve-log:\n")
	b.WriteString("      enabled: yes\n")
	b.WriteString("      filetype: regular\n")
	b.WriteString("      filename: eve.json\n")
	b.WriteString("      types:\n")
	b.WriteString("        - alert\n")
	b.WriteString("        - http\n")
	b.WriteString("        - dns\n")
	b.WriteString("        - tls\n")
	b.WriteString("        - flow\n\n")

	if ids.Prevent {
		// Inline NFQUEUE; the nftables renderer adds the matching queue
		// rule. "accept" verdicts packets that match no drop signature;
		// "fail-open" mirrors the nftables queue bypass flag.
		failOpen := "no"
		if ids.FailOpen {
			failOpen = "yes"
		}
		fmt.Fprintf(&b, "nfq:\n  mode: accept\n  fail-open: %s\n\n", failOpen)
	} else {
		b.WriteString("af-packet:\n")
		for i, ifc := range ids.Interfaces {
			fmt.Fprintf(&b, "  - interface: %s\n", ifc)
			fmt.Fprintf(&b, "    cluster-id: %d\n", 90+i)
			b.WriteString("    cluster-type: cluster_flow\n")
			b.WriteString("    defrag: yes\n")
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "default-rule-path: %s\n", opts.RulesDir)
	fmt.Fprintf(&b, "classification-file: %s\n", filepath.Join(opts.RulesDir, ClassificationFileName))
	fmt.Fprintf(&b, "reference-config-file: %s\n", filepath.Join(opts.RulesDir, ReferenceFileName))
	b.WriteString("rule-files:\n")
	for _, rf := range ids.RuleFiles {
		fmt.Fprintf(&b, "  - %s\n", rf)
	}
	appIDControls := appIDRuleControls(ir)
	if len(appIDControls) > 0 {
		fmt.Fprintf(&b, "  - %s\n", AppIDRuleFileName)
	}
	if len(ir.SecurityProfileRules) > 0 {
		fmt.Fprintf(&b, "  - %s\n", SecurityProfileRuleFileName)
	}
	b.WriteString("\n")
	if len(ids.Exceptions) > 0 {
		fmt.Fprintf(&b, "threshold-file: %s\n\n", filepath.Join(opts.RulesDir, ThresholdFileName))
		writeThresholdBlock(&b, ids.Exceptions)
	}
	if len(appIDControls) > 0 {
		writeAppIDRulesBlock(&b, appIDControls)
	}
	if len(ir.SecurityProfileRules) > 0 {
		writeSecurityProfileRulesBlock(&b, ir.SecurityProfileRules)
	}

	b.WriteString("app-layer:\n  protocols:\n    http:\n      enabled: yes\n    tls:\n      enabled: yes\n    dns:\n      tcp:\n        enabled: yes\n      udp:\n        enabled: yes\n    ssh:\n      enabled: yes\n\n")
	b.WriteString("logging:\n  default-log-level: notice\n  outputs:\n    - console:\n        enabled: yes\n")

	return []byte(b.String()), nil
}

func writeThresholdBlock(b *strings.Builder, exceptions []compiler.IDSExceptionIR) {
	b.WriteString("# Generated IDS false-positive controls. The engine writes\n")
	b.WriteString("# this block to the threshold-file path before validation/apply.\n")
	b.WriteString(thresholdBegin + "\n")
	for _, ex := range exceptions {
		fmt.Fprintf(b, "# ids_exception=%s", ex.Name)
		if ex.ThreatID != "" {
			fmt.Fprintf(b, " threat_id=%s", metadataValue(ex.ThreatID))
		}
		if ex.Description != "" {
			fmt.Fprintf(b, " description=%s", metadataValue(ex.Description))
		}
		if ex.Owner != "" {
			fmt.Fprintf(b, " owner=%s", metadataValue(ex.Owner))
		}
		if ex.TicketID != "" {
			fmt.Fprintf(b, " ticket=%s", metadataValue(ex.TicketID))
		}
		if ex.ReviewDate != "" {
			fmt.Fprintf(b, " review_date=%s", metadataValue(ex.ReviewDate))
		}
		if ex.ExpiresAt != "" {
			fmt.Fprintf(b, " expires_at=%s", metadataValue(ex.ExpiresAt))
		}
		if ex.PCAPSHA256 != "" {
			fmt.Fprintf(b, " pcap_sha256=%s", metadataValue(ex.PCAPSHA256))
		}
		if ex.Regression != "" {
			fmt.Fprintf(b, " regression_ref=%s", metadataValue(ex.Regression))
		}
		b.WriteString("\n")
		fmt.Fprintf(b, "# openngfw-threshold-line: suppress gen_id 1, sig_id %d", ex.SignatureID)
		if ex.Track != "" {
			fmt.Fprintf(b, ", track %s, ip %s", ex.Track, ex.Address.String())
		}
		b.WriteString("\n")
	}
	b.WriteString(thresholdEnd + "\n\n")
}

func appIDRuleControls(ir *compiler.IR) []compiler.AppIDControlIR {
	if len(ir.AppIDControls) > 0 {
		return ir.AppIDControls
	}
	var out []compiler.AppIDControlIR
	for _, drop := range ir.AppIDDrops {
		out = append(out, compiler.AppIDControlIR{
			RuleName:     drop.RuleName,
			Application:  drop.Application,
			EngineSignal: drop.EngineSignal,
			Action:       compiler.ActionDeny,
			Service:      compiler.ServiceMatch{Protocol: compiler.ProtoAny},
			SID:          drop.SID,
		})
	}
	return out
}

func writeAppIDRulesBlock(b *strings.Builder, controls []compiler.AppIDControlIR) {
	b.WriteString("# Generated App-ID allow/drop controls. The engine writes this\n")
	b.WriteString("# block to the managed App-ID rule file before validation/apply.\n")
	b.WriteString(appIDRulesBegin + "\n")
	for _, control := range controls {
		fmt.Fprintf(b, "# openngfw-appid-rule: %s\n", appIDControlRule(control))
	}
	b.WriteString(appIDRulesEnd + "\n\n")
}

func writeSecurityProfileRulesBlock(b *strings.Builder, rules []compiler.SecurityProfileRuleIR) {
	b.WriteString("# Generated security-profile inspection controls. The engine writes\n")
	b.WriteString("# this block to the managed security-profile rule file before validation/apply.\n")
	b.WriteString(securityProfileRulesBegin + "\n")
	for _, rule := range rules {
		fmt.Fprintf(b, "# openngfw-security-profile-rule: %s\n", securityProfileRule(rule))
	}
	b.WriteString(securityProfileRulesEnd + "\n\n")
}

func appIDControlRule(control compiler.AppIDControlIR) string {
	action := "drop"
	actionLabel := "deny"
	if control.Action == compiler.ActionAllow {
		action = "pass"
		actionLabel = "allow"
	}
	proto, src, srcPort, dst, dstPort := appIDControlHeader(control)
	msg := fmt.Sprintf("OpenNGFW App-ID %s %s via %s", actionLabel, control.Application, control.EngineSignal)
	meta := fmt.Sprintf("openngfw_rule %s, openngfw_application %s, openngfw_appid_action %s", control.RuleName, control.Application, actionLabel)
	if control.RuleID != "" {
		meta += ", openngfw_rule_id " + control.RuleID
	}
	return fmt.Sprintf("%s %s %s %s -> %s %s (msg:%q; app-layer-protocol:%s; metadata:%s; sid:%d; rev:1;)",
		action,
		proto,
		src,
		srcPort,
		dst,
		dstPort,
		oneLine(msg),
		control.EngineSignal,
		metadataValue(meta),
		control.SID,
	)
}

func appIDControlHeader(control compiler.AppIDControlIR) (proto, src, srcPort, dst, dstPort string) {
	proto = "ip"
	src = suricataAddressSet(control.SrcPrefixes)
	dst = suricataAddressSet(control.DstPrefixes)
	srcPort = "any"
	dstPort = "any"
	switch control.Service.Protocol {
	case compiler.ProtoTCP:
		proto = "tcp"
		dstPort = suricataPortSet(control.Service.Ports)
	case compiler.ProtoUDP:
		proto = "udp"
		dstPort = suricataPortSet(control.Service.Ports)
	}
	return proto, src, srcPort, dst, dstPort
}

func suricataAddressSet(prefixes []netip.Prefix) string {
	if len(prefixes) == 0 {
		return "any"
	}
	items := make([]string, len(prefixes))
	for i, prefix := range prefixes {
		items[i] = prefix.String()
	}
	if len(items) == 1 {
		return items[0]
	}
	return "[" + strings.Join(items, ",") + "]"
}

func suricataPortSet(ports []compiler.PortRange) string {
	if len(ports) == 0 {
		return "any"
	}
	items := make([]string, len(ports))
	for i, port := range ports {
		if port.Start == port.End {
			items[i] = fmt.Sprintf("%d", port.Start)
		} else {
			items[i] = fmt.Sprintf("%d:%d", port.Start, port.End)
		}
	}
	if len(items) == 1 {
		return items[0]
	}
	return "[" + strings.Join(items, ",") + "]"
}

func securityProfileRule(rule compiler.SecurityProfileRuleIR) string {
	msg := fmt.Sprintf("OpenNGFW security profile %s %s", rule.ProfileName, rule.Control)
	meta := fmt.Sprintf("openngfw_rule %s, openngfw_security_profile %s, openngfw_control %s", rule.RuleName, rule.ProfileName, rule.Control)
	return fmt.Sprintf("alert ip any any -> any any (msg:%q; app-layer-protocol:%s; metadata:%s; sid:%d; rev:1;)",
		oneLine(msg),
		rule.Protocol,
		metadataValue(meta),
		rule.SID,
	)
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func metadataValue(s string) string {
	v := oneLine(s)
	replacer := strings.NewReplacer(
		"# openngfw-threshold-line:", "openngfw-threshold-line:",
		"# openngfw-appid-rule:", "openngfw-appid-rule:",
		thresholdBegin, "openngfw-threshold-begin",
		thresholdEnd, "openngfw-threshold-end",
		appIDRulesBegin, "openngfw-appid-rules-begin",
		appIDRulesEnd, "openngfw-appid-rules-end",
		securityProfileRulesBegin, "openngfw-security-profile-rules-begin",
		securityProfileRulesEnd, "openngfw-security-profile-rules-end",
		"# openngfw-security-profile-rule:", "openngfw-security-profile-rule:",
	)
	return replacer.Replace(v)
}
