// Package suricata renders the IR's IDS section into a suricata.yaml.
//
// The first lines carry an "openngfw-mode" marker the engine supervisor
// reads to decide whether to run Suricata and in which mode — the
// artifact stays a single self-describing blob.
package suricata

import (
	"fmt"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// Options carries deployment paths that are not part of policy.
type Options struct {
	// RulesDir is the managed rule-file directory.
	RulesDir string
	// LogDir receives eve.json.
	LogDir string
}

// ModeMarker prefixes the mode line read by the engine supervisor.
const ModeMarker = "# openngfw-mode: "

// Mode strings used in the marker line.
const (
	ModeDisabled = "disabled"
	ModeDetect   = "detect"
	ModePrevent  = "prevent"
)

// Render produces suricata.yaml. When IDS is disabled the artifact is
// only the disabled marker — the supervisor stops any running instance.
func Render(ir *compiler.IR, opts Options) ([]byte, error) {
	var b strings.Builder
	if ir.IDs == nil {
		b.WriteString(ModeMarker + ModeDisabled + "\n")
		return []byte(b.String()), nil
	}
	ids := ir.IDs

	mode := ModeDetect
	if ids.Prevent {
		mode = ModePrevent
	}

	b.WriteString("%YAML 1.1\n---\n")
	b.WriteString(ModeMarker + mode + "\n")
	if ids.Prevent {
		fmt.Fprintf(&b, "# openngfw-queue: %d\n", ids.QueueNum)
	}
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n\n")

	homeNets := make([]string, len(ids.HomeNets))
	for i, p := range ids.HomeNets {
		homeNets[i] = p.String()
	}
	b.WriteString("vars:\n  address-groups:\n")
	fmt.Fprintf(&b, "    HOME_NET: \"[%s]\"\n", strings.Join(homeNets, ","))
	b.WriteString("    EXTERNAL_NET: \"!$HOME_NET\"\n\n")

	fmt.Fprintf(&b, "default-log-dir: %s\n\n", opts.LogDir)

	b.WriteString("stats:\n  enabled: no\n\n")

	b.WriteString("outputs:\n")
	b.WriteString("  - eve-log:\n")
	b.WriteString("      enabled: yes\n")
	b.WriteString("      filetype: regular\n")
	b.WriteString("      filename: eve.json\n")
	b.WriteString("      types:\n")
	b.WriteString("        - alert\n")
	b.WriteString("        - http\n")
	b.WriteString("        - dns\n")
	b.WriteString("        - tls\n")
	b.WriteString("        - flow\n\n")

	if ids.Prevent {
		// Inline NFQUEUE; the nftables renderer adds the matching queue
		// rule. "accept" verdicts packets that match no drop signature.
		b.WriteString("nfq:\n  mode: accept\n\n")
	} else {
		b.WriteString("af-packet:\n")
		for i, ifc := range ids.Interfaces {
			fmt.Fprintf(&b, "  - interface: %s\n", ifc)
			fmt.Fprintf(&b, "    cluster-id: %d\n", 90+i)
			b.WriteString("    cluster-type: cluster_flow\n")
			b.WriteString("    defrag: yes\n")
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "default-rule-path: %s\n", opts.RulesDir)
	b.WriteString("rule-files:\n")
	for _, rf := range ids.RuleFiles {
		fmt.Fprintf(&b, "  - %s\n", rf)
	}
	b.WriteString("\n")

	b.WriteString("app-layer:\n  protocols:\n    http:\n      enabled: yes\n    tls:\n      enabled: yes\n    dns:\n      tcp:\n        enabled: yes\n      udp:\n        enabled: yes\n\n")
	b.WriteString("logging:\n  default-log-level: notice\n  outputs:\n    - console:\n        enabled: yes\n")

	return []byte(b.String()), nil
}
