// Package wireguard renders the IR's WireGuard interfaces into a
// declarative text the wireguard engine executes via ip/wg. We do not
// use wg-quick because it requires the private key inline in its config
// file; the engine feeds the key to `wg set` straight from the
// operator-provisioned key file instead.
package wireguard

import (
	"fmt"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// InterfaceMarker introduces each interface block in the artifact.
const InterfaceMarker = "interface "

// Render produces the wireguard artifact. An empty artifact (no
// interfaces) tells the engine to tear down everything it manages.
func Render(ir *compiler.IR) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n")
	if ir.VPN == nil {
		return []byte(b.String()), nil
	}
	for _, w := range ir.VPN.Wireguard {
		fmt.Fprintf(&b, "%s%s\n", InterfaceMarker, w.Name)
		fmt.Fprintf(&b, "address %s\n", w.Address)
		if w.ListenPort != 0 {
			fmt.Fprintf(&b, "listen-port %d\n", w.ListenPort)
		}
		fmt.Fprintf(&b, "private-key-file %s\n", w.PrivateKeyFile)
		for _, p := range w.Peers {
			fmt.Fprintf(&b, "peer %s\n", p.PublicKey)
			if p.Endpoint != "" {
				fmt.Fprintf(&b, "  endpoint %s\n", p.Endpoint)
			}
			ips := make([]string, len(p.AllowedIPs))
			for i, ip := range p.AllowedIPs {
				ips[i] = ip.String()
			}
			fmt.Fprintf(&b, "  allowed-ips %s\n", strings.Join(ips, ","))
			if p.Keepalive != 0 {
				fmt.Fprintf(&b, "  keepalive %d\n", p.Keepalive)
			}
		}
	}
	return []byte(b.String()), nil
}
