// Package nftables renders the IR into a complete nftables ruleset.
//
// The output is a single file executed atomically by `nft -f`: it
// declares-then-deletes the openngfw table and redefines it, so a commit
// either fully applies or leaves the previous ruleset untouched.
//
// The renderer is pure ((IR) -> bytes) and deterministic — no
// timestamps, no map iteration — so golden-file tests are exact.
package nftables

import (
	"fmt"
	"net/netip"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// TableName is the nftables table owned by OpenNGFW. Only this table is
// ever touched; rulesets from other tools are left alone.
const TableName = "openngfw"

// Render produces the full ruleset for ir.
func Render(ir *compiler.IR) ([]byte, error) {
	var b strings.Builder
	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n\n")

	// Declare-then-delete makes the delete a no-op on first run and an
	// atomic replace afterwards.
	fmt.Fprintf(&b, "table inet %s\n", TableName)
	fmt.Fprintf(&b, "delete table inet %s\n\n", TableName)

	fmt.Fprintf(&b, "table inet %s {\n", TableName)

	if ir.Intel != nil && ir.Intel.Enabled {
		// Blocklist sets are populated by the intel updater out of band;
		// the ruleset only declares them and the drop rules.
		b.WriteString("\tset intel4 {\n\t\ttype ipv4_addr\n\t\tflags interval\n\t}\n\n")
		b.WriteString("\tset intel6 {\n\t\ttype ipv6_addr\n\t\tflags interval\n\t}\n\n")
	}

	// Host-input hardening is deliberately out of M1 scope (the v1 use
	// case filters *forwarded* traffic; a drop-by-default input chain
	// would lock operators out of management). Tracked for the M5 self-
	// zone work.
	b.WriteString("\tchain input {\n")
	b.WriteString("\t\ttype filter hook input priority filter; policy accept;\n")
	b.WriteString("\t\tct state invalid drop\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tchain forward {\n")
	b.WriteString("\t\ttype filter hook forward priority filter; policy drop;\n")
	// Inline IPS: every forwarded packet visits Suricata via NFQUEUE
	// before policy evaluation (stream reassembly needs the whole flow).
	// "bypass" fails open if Suricata is not consuming the queue.
	if ir.IDs != nil && ir.IDs.Prevent {
		fmt.Fprintf(&b, "\t\tcounter queue flags bypass to %d comment \"ips-inspect\"\n", ir.IDs.QueueNum)
	}
	// MSS clamp sits before the established accept so both SYN and the
	// returning SYN-ACK are rewritten (mixed-MTU paths: jumbo inside,
	// 1500 outside, tunnels).
	if ir.Network != nil && ir.Network.ClampMSS {
		b.WriteString("\t\ttcp flags syn tcp option maxseg size set rt mtu counter comment \"mss-clamp\"\n")
	}
	b.WriteString("\t\tct state established,related accept\n")
	b.WriteString("\t\tct state invalid drop\n")
	if ir.Intel != nil && ir.Intel.Enabled {
		b.WriteString("\t\tip saddr @intel4 log prefix \"ngfw:intel-block: \" counter drop comment \"intel-block-src\"\n")
		b.WriteString("\t\tip daddr @intel4 log prefix \"ngfw:intel-block: \" counter drop comment \"intel-block-dst\"\n")
		b.WriteString("\t\tip6 saddr @intel6 log prefix \"ngfw:intel-block: \" counter drop comment \"intel-block-src6\"\n")
		b.WriteString("\t\tip6 daddr @intel6 log prefix \"ngfw:intel-block: \" counter drop comment \"intel-block-dst6\"\n")
	}
	for _, r := range ir.Rules {
		lines, err := ruleLines(r)
		if err != nil {
			return nil, err
		}
		for _, l := range lines {
			b.WriteString("\t\t" + l + "\n")
		}
	}
	b.WriteString("\t\tcounter comment \"default-drop\"\n")
	b.WriteString("\t}\n")

	if len(ir.DNAT) > 0 {
		b.WriteString("\n\tchain nat_prerouting {\n")
		b.WriteString("\t\ttype nat hook prerouting priority dstnat; policy accept;\n")
		for _, d := range ir.DNAT {
			line, err := dnatLine(d)
			if err != nil {
				return nil, err
			}
			b.WriteString("\t\t" + line + "\n")
		}
		b.WriteString("\t}\n")
	}

	if len(ir.SNAT) > 0 {
		b.WriteString("\n\tchain nat_postrouting {\n")
		b.WriteString("\t\ttype nat hook postrouting priority srcnat; policy accept;\n")
		for _, s := range ir.SNAT {
			b.WriteString("\t\t" + snatLine(s) + "\n")
		}
		b.WriteString("\t}\n")
	}

	b.WriteString("}\n")
	return []byte(b.String()), nil
}

// family selects which address-family variant of a rule line to emit.
type family int

const (
	famAny family = iota // no address constraints
	famV4
	famV6
)

// ruleLines expands one IR rule into nft statements: one line per
// (address family × service match) combination that can apply.
func ruleLines(r compiler.RuleIR) ([]string, error) {
	src4, src6 := splitFamily(r.SrcPrefixes)
	dst4, dst6 := splitFamily(r.DstPrefixes)

	var fams []family
	switch {
	case len(r.SrcPrefixes) == 0 && len(r.DstPrefixes) == 0:
		fams = []family{famAny}
	default:
		// Emit a v4 line unless one side is exclusively v6, and vice versa.
		v4OK := (len(r.SrcPrefixes) == 0 || len(src4) > 0) && (len(r.DstPrefixes) == 0 || len(dst4) > 0)
		v6OK := (len(r.SrcPrefixes) == 0 || len(src6) > 0) && (len(r.DstPrefixes) == 0 || len(dst6) > 0)
		if v4OK {
			fams = append(fams, famV4)
		}
		if v6OK {
			fams = append(fams, famV6)
		}
		if len(fams) == 0 {
			return nil, fmt.Errorf("rule %q: source and destination address families do not overlap", r.Name)
		}
	}

	services := r.Services
	if len(services) == 0 {
		services = []compiler.ServiceMatch{{Protocol: compiler.ProtoAny}}
	}

	var lines []string
	for _, fam := range fams {
		for _, svc := range services {
			var parts []string
			if m := ifaceMatch("iifname", r.FromIfaces); m != "" {
				parts = append(parts, m)
			}
			if m := ifaceMatch("oifname", r.ToIfaces); m != "" {
				parts = append(parts, m)
			}
			switch fam {
			case famV4:
				if len(src4) > 0 {
					parts = append(parts, "ip saddr "+prefixSet(src4))
				}
				if len(dst4) > 0 {
					parts = append(parts, "ip daddr "+prefixSet(dst4))
				}
			case famV6:
				if len(src6) > 0 {
					parts = append(parts, "ip6 saddr "+prefixSet(src6))
				}
				if len(dst6) > 0 {
					parts = append(parts, "ip6 daddr "+prefixSet(dst6))
				}
			}
			if m := serviceMatch(svc, fam); m != "" {
				parts = append(parts, m)
			}
			if r.Log {
				parts = append(parts, fmt.Sprintf("log prefix %q", "ngfw:"+r.Name+": "))
			}
			parts = append(parts, "counter", verdict(r.Action), fmt.Sprintf("comment %q", "rule:"+r.Name))
			lines = append(lines, strings.Join(parts, " "))
		}
	}
	return lines, nil
}

func verdict(a compiler.RuleAction) string {
	switch a {
	case compiler.ActionAllow:
		return "accept"
	case compiler.ActionReject:
		return "reject"
	default:
		return "drop"
	}
}

func splitFamily(prefixes []netip.Prefix) (v4, v6 []netip.Prefix) {
	for _, p := range prefixes {
		if p.Addr().Is4() {
			v4 = append(v4, p)
		} else {
			v6 = append(v6, p)
		}
	}
	return v4, v6
}

func ifaceMatch(key string, ifaces []string) string {
	switch len(ifaces) {
	case 0:
		return ""
	case 1:
		return fmt.Sprintf("%s %q", key, ifaces[0])
	default:
		quoted := make([]string, len(ifaces))
		for i, ifc := range ifaces {
			quoted[i] = fmt.Sprintf("%q", ifc)
		}
		return fmt.Sprintf("%s { %s }", key, strings.Join(quoted, ", "))
	}
}

func prefixSet(prefixes []netip.Prefix) string {
	items := make([]string, len(prefixes))
	for i, p := range prefixes {
		items[i] = prefixString(p)
	}
	if len(items) == 1 {
		return items[0]
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func prefixString(p netip.Prefix) string {
	if p.IsSingleIP() {
		return p.Addr().String()
	}
	return p.String()
}

func serviceMatch(m compiler.ServiceMatch, fam family) string {
	switch m.Protocol {
	case compiler.ProtoTCP, compiler.ProtoUDP:
		proto := "tcp"
		if m.Protocol == compiler.ProtoUDP {
			proto = "udp"
		}
		if len(m.Ports) == 0 {
			return "meta l4proto " + proto
		}
		return fmt.Sprintf("%s dport %s", proto, portSet(m.Ports))
	case compiler.ProtoICMP:
		switch fam {
		case famV4:
			return "meta l4proto icmp"
		case famV6:
			return "meta l4proto ipv6-icmp"
		default:
			return "meta l4proto { icmp, ipv6-icmp }"
		}
	default:
		return ""
	}
}

func portSet(ports []compiler.PortRange) string {
	items := make([]string, len(ports))
	for i, pr := range ports {
		if pr.Start == pr.End {
			items[i] = fmt.Sprintf("%d", pr.Start)
		} else {
			items[i] = fmt.Sprintf("%d-%d", pr.Start, pr.End)
		}
	}
	if len(items) == 1 {
		return items[0]
	}
	return "{ " + strings.Join(items, ", ") + " }"
}

func dnatLine(d compiler.DNATIR) (string, error) {
	var parts []string
	if m := ifaceMatch("iifname", d.InIfaces); m != "" {
		parts = append(parts, m)
	}
	ipKw := "ip"
	if d.MatchDst.Is6() {
		ipKw = "ip6"
	}
	parts = append(parts, fmt.Sprintf("%s daddr %s", ipKw, d.MatchDst))

	proto := "tcp"
	switch d.Protocol {
	case compiler.ProtoTCP:
	case compiler.ProtoUDP:
		proto = "udp"
	default:
		return "", fmt.Errorf("destination-nat %q: protocol must be TCP or UDP", d.Name)
	}
	if len(d.Ports) == 0 {
		return "", fmt.Errorf("destination-nat %q: service must define ports", d.Name)
	}
	parts = append(parts, fmt.Sprintf("%s dport %s", proto, portSet(d.Ports)))

	target := d.TranslateTo.String()
	if d.TranslateTo.Is6() {
		target = "[" + target + "]"
	}
	if d.ToPort != 0 {
		target = fmt.Sprintf("%s:%d", target, d.ToPort)
	}
	toKw := "ip"
	if d.TranslateTo.Is6() {
		toKw = "ip6"
	}
	parts = append(parts, "counter", fmt.Sprintf("dnat %s to %s", toKw, target), fmt.Sprintf("comment %q", "dnat:"+d.Name))
	return strings.Join(parts, " "), nil
}

func snatLine(s compiler.SNATIR) string {
	var parts []string
	if m := ifaceMatch("oifname", s.OutIfaces); m != "" {
		parts = append(parts, m)
	}
	if s.SrcPrefix != nil {
		ipKw := "ip"
		if s.SrcPrefix.Addr().Is6() {
			ipKw = "ip6"
		}
		parts = append(parts, fmt.Sprintf("%s saddr %s", ipKw, prefixString(*s.SrcPrefix)))
	}
	parts = append(parts, "counter")
	if s.Masquerade {
		parts = append(parts, "masquerade")
	} else {
		toKw := "ip"
		if s.TranslateTo.Is6() {
			toKw = "ip6"
		}
		parts = append(parts, fmt.Sprintf("snat %s to %s", toKw, s.TranslateTo))
	}
	parts = append(parts, fmt.Sprintf("comment %q", "snat:"+s.Name))
	return strings.Join(parts, " ")
}
