// Package strongswan renders the IR's IPsec tunnels into swanctl.conf.
// Secrets never enter the artifact: each tunnel includes the operator-
// provisioned secrets snippet referenced by psk_file.
package strongswan

import (
	"fmt"
	"net/netip"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// ModeMarker prefixes the mode line read by the engine supervisor.
const ModeMarker = "# openngfw-mode: "

// Mode strings used in the marker line.
const (
	ModeDisabled = "disabled"
	ModeEnabled  = "enabled"
)

// Render produces swanctl.conf.
func Render(ir *compiler.IR) ([]byte, error) {
	var b strings.Builder
	if ir.VPN == nil || len(ir.VPN.IPsec) == 0 {
		b.WriteString(ModeMarker + ModeDisabled + "\n")
		return []byte(b.String()), nil
	}

	b.WriteString(ModeMarker + ModeEnabled + "\n")
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n\n")

	b.WriteString("connections {\n")
	for _, t := range ir.VPN.IPsec {
		fmt.Fprintf(&b, "    %s {\n", t.Name)
		b.WriteString("        version = 2\n")
		fmt.Fprintf(&b, "        local_addrs = %s\n", t.LocalAddress)
		fmt.Fprintf(&b, "        remote_addrs = %s\n", t.RemoteAddress)
		fmt.Fprintf(&b, "        proposals = %s\n", t.IKEProposal)
		b.WriteString("        local {\n            auth = psk\n        }\n")
		b.WriteString("        remote {\n            auth = psk\n        }\n")
		b.WriteString("        children {\n")
		fmt.Fprintf(&b, "            %s {\n", t.Name)
		fmt.Fprintf(&b, "                local_ts = %s\n", joinPrefixes(t.LocalSubnets))
		fmt.Fprintf(&b, "                remote_ts = %s\n", joinPrefixes(t.RemoteSubnets))
		fmt.Fprintf(&b, "                esp_proposals = %s\n", t.ESPProposal)
		if t.Initiate {
			b.WriteString("                start_action = start\n")
		} else {
			b.WriteString("                start_action = trap\n")
		}
		b.WriteString("            }\n")
		b.WriteString("        }\n")
		b.WriteString("    }\n")
	}
	b.WriteString("}\n\n")

	// Operator-owned PSK snippets; controld never sees key material.
	seen := map[string]bool{}
	for _, t := range ir.VPN.IPsec {
		if !seen[t.PSKFile] {
			fmt.Fprintf(&b, "include %s\n", t.PSKFile)
			seen[t.PSKFile] = true
		}
	}
	return []byte(b.String()), nil
}

func joinPrefixes(prefixes []netip.Prefix) string {
	items := make([]string, len(prefixes))
	for i, p := range prefixes {
		items[i] = p.String()
	}
	return strings.Join(items, ",")
}
