package engines

import (
	"bufio"
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// SuricataName keys the suricata.yaml artifact.
const SuricataName = "suricata"

const (
	suricataThresholdFile           = "openngfw-threshold.config"
	suricataClassFile               = "openngfw-classification.config"
	suricataReferenceFile           = "openngfw-reference.config"
	suricataAppIDRuleFile           = "openngfw-appid.rules"
	suricataSecurityProfileRuleFile = "openngfw-security-profiles.rules"
	thresholdBlockBegin             = "# openngfw-threshold-begin"
	thresholdBlockEnd               = "# openngfw-threshold-end"
	thresholdLinePrefix             = "# openngfw-threshold-line: "
	appIDRulesBlockBegin            = "# openngfw-appid-rules-begin"
	appIDRulesBlockEnd              = "# openngfw-appid-rules-end"
	appIDRuleLinePrefix             = "# openngfw-appid-rule: "
	securityProfileRulesBlockBegin  = "# openngfw-security-profile-rules-begin"
	securityProfileRulesBlockEnd    = "# openngfw-security-profile-rules-end"
	securityProfileRuleLinePrefix   = "# openngfw-security-profile-rule: "
	thresholdGeneratedHdr           = "# Generated by OpenNGFW controld. Do not edit; overwritten on every commit."
)

// Suricata supervises the Suricata IDS/IPS process. The rendered
// artifact carries an "openngfw-mode:" marker (disabled/detect/prevent)
// that selects run mode; config changes restart the process.
type Suricata struct {
	// Binary is the suricata executable; defaults to "suricata".
	Binary string
	// StateDir holds suricata.yaml and the rules/ directory.
	StateDir string
	// LogDir receives eve.json (must match the renderer Options).
	LogDir string

	proc procManager
}

// Name implements Engine.
func (s *Suricata) Name() string { return SuricataName }

func (s *Suricata) bin() string {
	if s.Binary != "" {
		return s.Binary
	}
	return "suricata"
}

type suricataMode struct {
	mode       string
	queueNum   string
	queueCount int
}

func parseMode(config []byte) suricataMode {
	m := suricataMode{mode: "disabled", queueNum: "0", queueCount: 1}
	sc := bufio.NewScanner(bytes.NewReader(config))
	for sc.Scan() {
		line := sc.Text()
		if v, ok := strings.CutPrefix(line, "# openngfw-mode: "); ok {
			m.mode = strings.TrimSpace(v)
		}
		if v, ok := strings.CutPrefix(line, "# openngfw-queue: "); ok {
			m.queueNum = strings.TrimSpace(v)
		}
		if v, ok := strings.CutPrefix(line, "# openngfw-queue-count: "); ok {
			if n, err := strconv.Atoi(strings.TrimSpace(v)); err == nil && n > 0 {
				m.queueCount = n
			}
		}
	}
	return m
}

// ensureRuleFiles creates the rules dir and any missing referenced rule
// files (empty) so `suricata -T` can resolve them; operators populate
// them via suricata-update or drop-ins.
func (s *Suricata) ensureRuleFiles(config []byte) error {
	rulesDir := filepath.Join(s.StateDir, "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return err
	}
	sc := bufio.NewScanner(bytes.NewReader(config))
	inRuleFiles := false
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "rule-files:") {
			inRuleFiles = true
			continue
		}
		if inRuleFiles {
			name, ok := strings.CutPrefix(line, "  - ")
			if !ok {
				inRuleFiles = false
				continue
			}
			path := filepath.Join(rulesDir, strings.TrimSpace(name))
			if _, err := os.Stat(path); os.IsNotExist(err) {
				if err := os.WriteFile(path, nil, 0o644); err != nil {
					return err
				}
			}
		}
	}
	return sc.Err()
}

func (s *Suricata) ensureThresholdFile(config []byte) error {
	lines, ok, err := thresholdLines(config)
	if err != nil || !ok {
		return err
	}
	rulesDir := filepath.Join(s.StateDir, "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return err
	}
	content := thresholdGeneratedHdr + "\n"
	if len(lines) > 0 {
		content += strings.Join(lines, "\n") + "\n"
	}
	return os.WriteFile(filepath.Join(rulesDir, suricataThresholdFile), []byte(content), 0o644)
}

func (s *Suricata) ensureClassificationFile(config []byte) error {
	return s.ensureManagedMetadataFile(config, suricataClassFile)
}

func (s *Suricata) ensureReferenceFile(config []byte) error {
	return s.ensureManagedMetadataFile(config, suricataReferenceFile)
}

func (s *Suricata) ensureManagedMetadataFile(config []byte, name string) error {
	if !bytes.Contains(config, []byte(name)) {
		return nil
	}
	rulesDir := filepath.Join(s.StateDir, "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(rulesDir, name)
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(path, []byte(thresholdGeneratedHdr+"\n"), 0o644)
}

func (s *Suricata) ensureAppIDRuleFile(config []byte) error {
	lines, ok, err := generatedBlockLines(config, appIDRulesBlockBegin, appIDRulesBlockEnd, appIDRuleLinePrefix)
	if err != nil || !ok {
		return err
	}
	rulesDir := filepath.Join(s.StateDir, "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return err
	}
	content := thresholdGeneratedHdr + "\n"
	if len(lines) > 0 {
		content += strings.Join(lines, "\n") + "\n"
	}
	return os.WriteFile(filepath.Join(rulesDir, suricataAppIDRuleFile), []byte(content), 0o644)
}

func (s *Suricata) ensureSecurityProfileRuleFile(config []byte) error {
	lines, ok, err := generatedBlockLines(config, securityProfileRulesBlockBegin, securityProfileRulesBlockEnd, securityProfileRuleLinePrefix)
	if err != nil || !ok {
		return err
	}
	rulesDir := filepath.Join(s.StateDir, "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return err
	}
	content := thresholdGeneratedHdr + "\n"
	if len(lines) > 0 {
		content += strings.Join(lines, "\n") + "\n"
	}
	return os.WriteFile(filepath.Join(rulesDir, suricataSecurityProfileRuleFile), []byte(content), 0o644)
}

func thresholdLines(config []byte) ([]string, bool, error) {
	return generatedBlockLines(config, thresholdBlockBegin, thresholdBlockEnd, thresholdLinePrefix)
}

func generatedBlockLines(config []byte, begin, end, prefix string) ([]string, bool, error) {
	var out []string
	inBlock := false
	found := false
	sc := bufio.NewScanner(bytes.NewReader(config))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		switch line {
		case begin:
			inBlock = true
			found = true
			continue
		case end:
			inBlock = false
			continue
		}
		if inBlock {
			if value, ok := strings.CutPrefix(line, prefix); ok {
				out = append(out, strings.TrimSpace(value))
			}
		}
	}
	if err := sc.Err(); err != nil {
		return nil, found, err
	}
	if inBlock {
		return nil, found, fmt.Errorf("unterminated %s block", begin)
	}
	return out, found, nil
}

// Validate runs `suricata -T` against the rendered config.
func (s *Suricata) Validate(ctx context.Context, config []byte) error {
	if parseMode(config).mode == "disabled" {
		return nil
	}
	if _, err := exec.LookPath(s.bin()); err != nil {
		return fmt.Errorf("policy enables IDS but %s is not installed: %w", s.bin(), err)
	}
	if err := s.ensureRuleFiles(config); err != nil {
		return err
	}
	if err := s.ensureThresholdFile(config); err != nil {
		return err
	}
	if err := s.ensureClassificationFile(config); err != nil {
		return err
	}
	if err := s.ensureReferenceFile(config); err != nil {
		return err
	}
	if err := s.ensureAppIDRuleFile(config); err != nil {
		return err
	}
	if err := s.ensureSecurityProfileRuleFile(config); err != nil {
		return err
	}
	if err := os.MkdirAll(s.LogDir, 0o755); err != nil {
		return err
	}
	tmp, err := writeTemp(config, "openngfw-suricata-*.yaml")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp) }()
	return runCmd(ctx, s.bin(), "-T", "-c", tmp)
}

// Apply writes the config and (re)starts or stops Suricata accordingly.
func (s *Suricata) Apply(_ context.Context, config []byte) error {
	mode := parseMode(config)
	if mode.mode == "disabled" {
		s.proc.stop()
		return nil
	}
	if err := s.ensureRuleFiles(config); err != nil {
		return err
	}
	if err := s.ensureThresholdFile(config); err != nil {
		return err
	}
	if err := s.ensureClassificationFile(config); err != nil {
		return err
	}
	if err := s.ensureReferenceFile(config); err != nil {
		return err
	}
	if err := s.ensureAppIDRuleFile(config); err != nil {
		return err
	}
	if err := s.ensureSecurityProfileRuleFile(config); err != nil {
		return err
	}
	if err := os.MkdirAll(s.LogDir, 0o755); err != nil {
		return err
	}
	cfgPath := filepath.Join(s.StateDir, "suricata.yaml")
	if err := os.WriteFile(cfgPath, config, 0o644); err != nil {
		return err
	}
	switch mode.mode {
	case "detect":
		return s.proc.restart(s.bin(), "-c", cfgPath, "--af-packet")
	case "prevent":
		// One -q per NFQUEUE in the fan-out range [base, base+count);
		// the runmode:workers config gives each its own worker thread.
		base, err := strconv.Atoi(mode.queueNum)
		if err != nil {
			return fmt.Errorf("invalid queue number %q: %w", mode.queueNum, err)
		}
		args := []string{"-c", cfgPath}
		for i := 0; i < mode.queueCount; i++ {
			args = append(args, "-q", strconv.Itoa(base+i))
		}
		return s.proc.restart(s.bin(), args...)
	default:
		return fmt.Errorf("unknown suricata mode %q", mode.mode)
	}
}

// Stop terminates a running Suricata (daemon shutdown).
func (s *Suricata) Stop() { s.proc.stop() }

// Status reports the supervised Suricata child lifecycle.
func (s *Suricata) Status() ProcessStatus { return s.proc.Status() }
