package engines

import (
	"context"
	"os"
	"strings"
	"testing"
)

const wgArtifact = `# Generated by OpenNGFW controld.
interface wg0
address 10.99.0.1/24
listen-port 51820
private-key-file /etc/openngfw/keys/wg0.key
peer pubkey1=
  endpoint 203.0.113.5:51820
  allowed-ips 10.99.0.2/32
  keepalive 25
peer pubkey2=
  allowed-ips 10.99.0.3/32
interface wg1
address 10.98.0.1/24
private-key-file /etc/openngfw/keys/wg1.key
`

func TestParseWireguard(t *testing.T) {
	ifaces, err := parseWireguard([]byte(wgArtifact))
	if err != nil {
		t.Fatal(err)
	}
	if len(ifaces) != 2 {
		t.Fatalf("want 2 interfaces, got %d", len(ifaces))
	}
	wg0 := ifaces[0]
	if wg0.name != "wg0" || wg0.address != "10.99.0.1/24" || wg0.listenPort != "51820" {
		t.Errorf("wg0 = %+v", wg0)
	}
	if len(wg0.peers) != 2 {
		t.Fatalf("wg0 peers = %+v", wg0.peers)
	}
	if wg0.peers[0].endpoint != "203.0.113.5:51820" || wg0.peers[0].keepalive != "25" {
		t.Errorf("peer1 = %+v", wg0.peers[0])
	}
	if wg0.peers[1].endpoint != "" || wg0.peers[1].allowedIPs != "10.99.0.3/32" {
		t.Errorf("peer2 = %+v", wg0.peers[1])
	}
	if ifaces[1].name != "wg1" || ifaces[1].listenPort != "" {
		t.Errorf("wg1 = %+v", ifaces[1])
	}
}

func TestParseWireguardErrors(t *testing.T) {
	for name, artifact := range map[string]string{
		"directive before interface": "address 10.0.0.1/24\n",
		"peer attr before peer":      "interface wg0\nendpoint 1.2.3.4:1\n",
		"unknown directive":          "interface wg0\nbogus x\n",
	} {
		if _, err := parseWireguard([]byte(artifact)); err == nil {
			t.Errorf("%s: expected parse error", name)
		}
	}
}

func TestWireguardApplyRemovesStalePeers(t *testing.T) {
	dir := t.TempDir()
	var calls []string
	w := &Wireguard{
		StateDir: dir,
		run: func(_ context.Context, name string, args ...string) error {
			calls = append(calls, name+" "+strings.Join(args, " "))
			return nil
		},
		output: func(_ context.Context, name string, args ...string) ([]byte, error) {
			calls = append(calls, name+" "+strings.Join(args, " "))
			if name == "wg" && strings.Join(args, " ") == "show wg0 peers" {
				return []byte("stale-key=\npubkey1=\n"), nil
			}
			return nil, nil
		},
	}
	artifact := `interface wg0
address 10.99.0.1/24
private-key-file /tmp/wg0.key
peer pubkey1=
  allowed-ips 10.99.0.2/32
`
	if err := w.Apply(context.Background(), []byte(artifact)); err != nil {
		t.Fatal(err)
	}
	if !hasCall(calls, "wg show wg0 peers") {
		t.Fatalf("calls = %v, want current peer inventory", calls)
	}
	if !hasCall(calls, "wg set wg0 peer stale-key= remove") {
		t.Fatalf("calls = %v, want stale peer removal", calls)
	}
	if hasCall(calls, "wg set wg0 peer pubkey1= remove") {
		t.Fatalf("calls = %v, retained peer was removed", calls)
	}
	if !hasCall(calls, "wg set wg0 private-key /tmp/wg0.key peer pubkey1= allowed-ips 10.99.0.2/32") {
		t.Fatalf("calls = %v, want desired peer set", calls)
	}
}

func TestFRRParseDaemons(t *testing.T) {
	cfg := []byte(ModeFRRHeader("bgpd,ospfd") + "frr defaults traditional\n")
	got := parseDaemons(cfg)
	if len(got) != 2 || got[0] != "bgpd" || got[1] != "ospfd" {
		t.Fatalf("parseDaemons = %v", got)
	}
	if parseDaemons([]byte(ModeFRRHeader("none"))) != nil {
		t.Fatal("none must parse as no daemons")
	}
}

func hasCall(calls []string, want string) bool {
	for _, call := range calls {
		if call == want {
			return true
		}
	}
	return false
}

// ModeFRRHeader builds an FRR marker line for tests.
func ModeFRRHeader(daemons string) string { return "! openngfw-daemons: " + daemons + "\n" }

func TestFRREnableDaemons(t *testing.T) {
	dir := t.TempDir()
	daemonsFile := dir + "/daemons"
	orig := "zebra=yes\nbgpd=no\nospfd=no\nripd=no\nvtysh_enable=yes\n"
	if err := writeFile(daemonsFile, orig); err != nil {
		t.Fatal(err)
	}
	f := &FRR{DaemonsPath: daemonsFile}
	if err := f.enableDaemons([]string{"bgpd"}); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, daemonsFile)
	for _, want := range []string{"bgpd=yes", "ospfd=no", "zebra=yes", "ripd=no", "vtysh_enable=yes"} {
		if !strings.Contains(got, want) {
			t.Errorf("daemons file missing %q:\n%s", want, got)
		}
	}
}

func TestFRRApplyDisablesManagedDaemonsOnCleanup(t *testing.T) {
	dir := t.TempDir()
	daemonsFile := dir + "/daemons"
	configFile := dir + "/frr.conf"
	orig := "zebra=yes\nbgpd=no\nospfd=no\nripd=no\nvtysh_enable=yes\n"
	if err := writeFile(daemonsFile, orig); err != nil {
		t.Fatal(err)
	}
	f := &FRR{
		ConfigPath:  configFile,
		DaemonsPath: daemonsFile,
		ReloadCmd:   []string{"true"},
		StateDir:    dir,
	}
	if err := f.Apply(context.Background(), []byte(ModeFRRHeader("bgpd")+"\n")); err != nil {
		t.Fatal(err)
	}
	if got := readFile(t, daemonsFile); !strings.Contains(got, "bgpd=yes") {
		t.Fatalf("daemons after enable = %q, want bgpd=yes", got)
	}

	if err := f.Apply(context.Background(), []byte(ModeFRRHeader("none")+"\n")); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, daemonsFile)
	for _, want := range []string{"bgpd=no", "ospfd=no", "zebra=yes", "vtysh_enable=yes"} {
		if !strings.Contains(got, want) {
			t.Errorf("daemons after cleanup missing %q:\n%s", want, got)
		}
	}
	if _, err := os.Stat(f.markerPath()); !os.IsNotExist(err) {
		t.Fatalf("managed marker still present after cleanup: %v", err)
	}
}

func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}
