package engines

import (
	"os"
	"strings"
	"testing"
)

const wgArtifact = `# Generated by OpenNGFW controld.
interface wg0
address 10.99.0.1/24
listen-port 51820
private-key-file /etc/openngfw/keys/wg0.key
peer pubkey1=
  endpoint 203.0.113.5:51820
  allowed-ips 10.99.0.2/32
  keepalive 25
peer pubkey2=
  allowed-ips 10.99.0.3/32
interface wg1
address 10.98.0.1/24
private-key-file /etc/openngfw/keys/wg1.key
`

func TestParseWireguard(t *testing.T) {
	ifaces, err := parseWireguard([]byte(wgArtifact))
	if err != nil {
		t.Fatal(err)
	}
	if len(ifaces) != 2 {
		t.Fatalf("want 2 interfaces, got %d", len(ifaces))
	}
	wg0 := ifaces[0]
	if wg0.name != "wg0" || wg0.address != "10.99.0.1/24" || wg0.listenPort != "51820" {
		t.Errorf("wg0 = %+v", wg0)
	}
	if len(wg0.peers) != 2 {
		t.Fatalf("wg0 peers = %+v", wg0.peers)
	}
	if wg0.peers[0].endpoint != "203.0.113.5:51820" || wg0.peers[0].keepalive != "25" {
		t.Errorf("peer1 = %+v", wg0.peers[0])
	}
	if wg0.peers[1].endpoint != "" || wg0.peers[1].allowedIPs != "10.99.0.3/32" {
		t.Errorf("peer2 = %+v", wg0.peers[1])
	}
	if ifaces[1].name != "wg1" || ifaces[1].listenPort != "" {
		t.Errorf("wg1 = %+v", ifaces[1])
	}
}

func TestParseWireguardErrors(t *testing.T) {
	for name, artifact := range map[string]string{
		"directive before interface": "address 10.0.0.1/24\n",
		"peer attr before peer":      "interface wg0\nendpoint 1.2.3.4:1\n",
		"unknown directive":          "interface wg0\nbogus x\n",
	} {
		if _, err := parseWireguard([]byte(artifact)); err == nil {
			t.Errorf("%s: expected parse error", name)
		}
	}
}

func TestFRRParseDaemons(t *testing.T) {
	cfg := []byte(ModeFRRHeader("bgpd,ospfd") + "frr defaults traditional\n")
	got := parseDaemons(cfg)
	if len(got) != 2 || got[0] != "bgpd" || got[1] != "ospfd" {
		t.Fatalf("parseDaemons = %v", got)
	}
	if parseDaemons([]byte(ModeFRRHeader("none"))) != nil {
		t.Fatal("none must parse as no daemons")
	}
}

// ModeFRRHeader builds an FRR marker line for tests.
func ModeFRRHeader(daemons string) string { return "! openngfw-daemons: " + daemons + "\n" }

func TestFRREnableDaemons(t *testing.T) {
	dir := t.TempDir()
	daemonsFile := dir + "/daemons"
	orig := "zebra=yes\nbgpd=no\nospfd=no\nripd=no\nvtysh_enable=yes\n"
	if err := writeFile(daemonsFile, orig); err != nil {
		t.Fatal(err)
	}
	f := &FRR{DaemonsPath: daemonsFile}
	if err := f.enableDaemons([]string{"bgpd"}); err != nil {
		t.Fatal(err)
	}
	got := readFile(t, daemonsFile)
	for _, want := range []string{"bgpd=yes", "ospfd=no", "zebra=yes", "ripd=no", "vtysh_enable=yes"} {
		if !strings.Contains(got, want) {
			t.Errorf("daemons file missing %q:\n%s", want, got)
		}
	}
}

func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}
