// Package netdev renders the IR's global network settings into a
// declarative link-configuration artifact the netdev engine applies via
// ip/ethtool: managed MTUs and IDS offload state.
package netdev

import (
	"fmt"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// Render produces the netdev artifact. An artifact with no directives
// means nothing is managed (existing link settings are left alone).
func Render(ir *compiler.IR) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n")
	if ir.Network == nil {
		return []byte(b.String()), nil
	}
	for _, l := range ir.Network.Links {
		fmt.Fprintf(&b, "link %s mtu %d\n", l.Interface, l.MTU)
	}
	for _, ifc := range ir.Network.OffloadOffIfaces {
		// GRO/TSO/GSO hand the IDS reassembled super-packets; LRO is
		// intentionally not touched (fixed-off on most drivers, and
		// requesting it fails on some).
		fmt.Fprintf(&b, "offload %s off\n", ifc)
	}
	return []byte(b.String()), nil
}
