// Package netdev renders the IR's global network settings into a
// declarative link-configuration artifact the netdev engine applies via
// ip/ethtool: managed MTUs and IDS offload state.
package netdev

import (
	"fmt"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// Render produces the netdev artifact. An artifact with no directives
// means nothing is managed (existing link settings are left alone).
func Render(ir *compiler.IR) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n")
	if ir.Network != nil {
		for _, l := range ir.Network.Links {
			fmt.Fprintf(&b, "link %s mtu %d\n", l.Interface, l.MTU)
		}
		for _, ifc := range ir.Network.OffloadOffIfaces {
			// GRO/TSO/GSO hand the IDS reassembled super-packets; LRO is
			// intentionally not touched (fixed-off on most drivers, and
			// requesting it fails on some).
			fmt.Fprintf(&b, "offload %s off\n", ifc)
		}
	}
	for _, control := range ir.QoSControls {
		fmt.Fprintf(&b, "qos-plan rule %s profile %s state planned runtime unsupported max-kbps %d guaranteed-kbps %d priority %s dscp %d burst-kbytes %d\n",
			token(control.RuleName), token(control.ProfileName), control.MaxBandwidthKbps, control.GuaranteedBandwidthKbps, token(control.Priority), control.DSCPMark, control.BurstKBytes)
	}
	for _, protection := range ir.ZoneProtections {
		fmt.Fprintf(&b, "zone-protection-plan zone %s profile %s state planned runtime unsupported enabled %t action %s audit-log %t interfaces %s syn-pps %d udp-pps %d icmp-pps %d max-connections %d\n",
			token(protection.ZoneName), token(protection.ProfileName), protection.Enabled, token(protection.Action), protection.AuditLog, token(strings.Join(protection.Interfaces, ",")),
			protection.SynFloodPPS, protection.UDPFloodPPS, protection.ICMPFloodPPS, protection.MaxConcurrentConnections)
	}
	return []byte(b.String()), nil
}

func token(value string) string {
	if value == "" {
		return "-"
	}
	return strings.NewReplacer(" ", "_", "\t", "_", "\n", "_", "\r", "_").Replace(value)
}
