// Package vector renders the telemetry pipeline config: Suricata EVE
// JSON (and controld's own log file when present) shipped to ClickHouse.
// The same mode-marker convention as the suricata renderer applies.
package vector

import (
	"fmt"
	"strings"

	"github.com/detailtech/oss-ngfw/internal/compiler"
)

// Options carries deployment paths that are not part of policy.
type Options struct {
	// EvePath is the Suricata EVE JSON file to tail.
	EvePath string
	// DataDir is Vector's disk-buffer directory.
	DataDir string
}

// ModeMarker prefixes the mode line read by the engine supervisor.
const ModeMarker = "# openngfw-mode: "

// Mode strings used in the marker line.
const (
	ModeDisabled = "disabled"
	ModeEnabled  = "enabled"
)

// Render produces vector.yaml.
func Render(ir *compiler.IR, opts Options) ([]byte, error) {
	var b strings.Builder
	if ir.Telemetry == nil {
		b.WriteString(ModeMarker + ModeDisabled + "\n")
		return []byte(b.String()), nil
	}
	tel := ir.Telemetry

	b.WriteString(ModeMarker + ModeEnabled + "\n")
	b.WriteString("# Generated by OpenNGFW controld. Do not edit; overwritten on every commit.\n\n")
	fmt.Fprintf(&b, "data_dir: %s\n\n", opts.DataDir)

	b.WriteString("sources:\n")
	b.WriteString("  suricata_eve:\n")
	b.WriteString("    type: file\n")
	fmt.Fprintf(&b, "    include: [%q]\n", opts.EvePath)
	b.WriteString("\n")

	b.WriteString("transforms:\n")
	b.WriteString("  eve_parsed:\n")
	b.WriteString("    type: remap\n")
	b.WriteString("    inputs: [suricata_eve]\n")
	b.WriteString("    source: |\n")
	b.WriteString("      . = parse_json!(.message)\n")
	b.WriteString("      .ingested_at = now()\n")
	b.WriteString("  eve_alerts:\n")
	b.WriteString("    type: filter\n")
	b.WriteString("    inputs: [eve_parsed]\n")
	b.WriteString("    condition: .event_type == \"alert\"\n\n")

	b.WriteString("sinks:\n")
	b.WriteString("  clickhouse_events:\n")
	b.WriteString("    type: clickhouse\n")
	b.WriteString("    inputs: [eve_parsed]\n")
	fmt.Fprintf(&b, "    endpoint: %s\n", tel.ClickHouseURL)
	fmt.Fprintf(&b, "    database: %s\n", tel.Database)
	b.WriteString("    table: events\n")
	b.WriteString("    skip_unknown_fields: true\n")
	b.WriteString("  clickhouse_alerts:\n")
	b.WriteString("    type: clickhouse\n")
	b.WriteString("    inputs: [eve_alerts]\n")
	fmt.Fprintf(&b, "    endpoint: %s\n", tel.ClickHouseURL)
	fmt.Fprintf(&b, "    database: %s\n", tel.Database)
	b.WriteString("    table: alerts\n")
	b.WriteString("    skip_unknown_fields: true\n")

	return []byte(b.String()), nil
}
