// ngfwopenapi applies small hand-authored overlays to the generated Swagger
// document for management HTTP routes that are not backed by protobuf RPCs.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"strconv"

	"go.yaml.in/yaml/v3"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("ngfwopenapi", flag.ContinueOnError)
	in := fs.String("in", "", "input Swagger YAML")
	out := fs.String("out", "", "output Swagger YAML")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *in == "" || *out == "" {
		return errors.New("usage: ngfwopenapi --in api-spec.swagger.yaml --out api-spec.swagger.yaml")
	}
	raw, err := os.ReadFile(*in)
	if err != nil {
		return fmt.Errorf("read %s: %w", *in, err)
	}
	overlayed, err := overlay(raw)
	if err != nil {
		return err
	}
	if err := os.WriteFile(*out, overlayed, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	}
	return nil
}

func overlay(raw []byte) ([]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse generated Swagger YAML: %w", err)
	}
	root, err := documentMap(&doc)
	if err != nil {
		return nil, err
	}
	paths := ensureMap(root, "paths")
	setMap(paths, "/v1/auth/oidc/status", pathItem("get", oidcStatusOperation()))
	setMap(paths, "/v1/auth/oidc/login", pathItem("get", redirectOperation(
		"oidcLogin",
		"Start browser OIDC login",
		"Redirects the browser to the configured OIDC provider. This route is public on the management listener and does not accept bearer-token API authentication.",
		"OIDC login failed",
		[]*yaml.Node{stringParameter("return", "query", false, "Optional WebUI return path after successful login.")},
	)))
	setMap(paths, "/v1/auth/oidc/callback", pathItem("get", redirectOperation(
		"oidcCallback",
		"Complete browser OIDC login",
		"Consumes the provider authorization-code callback, validates state, PKCE, and nonce, then establishes an HttpOnly WebUI session cookie.",
		"OIDC login failed",
		[]*yaml.Node{
			stringParameter("code", "query", true, "OIDC authorization code."),
			stringParameter("state", "query", true, "Opaque login state generated by the firewall."),
		},
	)))
	setMap(paths, "/v1/auth/saml/status", pathItem("get", samlStatusOperation()))
	setMap(paths, "/v1/auth/saml/login", pathItem("get", redirectOperation(
		"samlLogin",
		"Start browser SAML login",
		"Redirects the browser to the configured SAML identity provider. This route is public on the management listener and does not accept bearer-token API authentication.",
		"SAML login failed",
		[]*yaml.Node{stringParameter("return", "query", false, "Optional WebUI return path after successful login.")},
	)))
	setMap(paths, "/v1/auth/saml/acs", pathItem("post", redirectOperation(
		"samlACS",
		"Complete browser SAML login",
		"Consumes the IdP SAMLResponse and RelayState, validates the assertion, then establishes an HttpOnly WebUI session cookie.",
		"SAML login failed",
		[]*yaml.Node{
			stringParameter("SAMLResponse", "formData", true, "Base64-encoded SAML response posted by the IdP."),
			stringParameter("RelayState", "formData", true, "Opaque login state generated by the firewall."),
		},
	)))
	setMap(paths, "/v1/auth/logout", pathItem("post", logoutOperation()))
	setMap(paths, "/v1/fleet/nodes", pathItem("get", fleetOperation(
		"listFleetNodes",
		"List fleet nodes",
		"Reports the connected local appliance as a bounded fleet inventory record. This is functional template/inventory plumbing, not authoritative multi-node fleet management.",
		nil,
	)))
	setMap(paths, "/v1/fleet/templates", mapping(
		"get", fleetOperation(
			"listFleetTemplates",
			"List fleet templates",
			"Lists server-retained local fleet template records.",
			nil,
		),
		"post", fleetCreatedOperation(
			"createFleetTemplate",
			"Create fleet template",
			"Stores a local template policy packet for validation and apply-preview workflows.",
			genericJSONBodyRef("CreateFleetTemplateRequest", "#/definitions/openngfw.v1.CreateFleetTemplateRequest"),
		),
	))
	setMap(paths, "/v1/fleet/templates/{id}:validate", pathItem("post", fleetOperation(
		"validateFleetTemplate",
		"Validate fleet template",
		"Validates one stored fleet template policy without changing candidate or running policy.",
		nil,
	)))
	setMap(paths, "/v1/fleet/templates/{id}:apply-preview", pathItem("post", fleetOperation(
		"applyPreviewFleetTemplate",
		"Preview fleet template apply",
		"Compares one stored fleet template with the current candidate and returns validation/impact context without applying it.",
		genericJSONBodyRef("ApplyPreviewFleetTemplateRequest", "#/definitions/openngfw.v1.ApplyPreviewFleetTemplateRequest"),
	)))
	setMap(paths, "/v1/fleet/templates/{id}:apply-plan", pathItem("post", fleetOperation(
		"applyPlanFleetTemplate",
		"Plan fleet template apply",
		"Builds a bounded per-node Fleet template apply plan from local and operator-supplied peer inventory without peer RPC or running-policy apply.",
		genericJSONBodyRef("ApplyPlanFleetTemplateRequest", "#/definitions/openngfw.v1.ApplyPlanFleetTemplateRequest"),
	)))
	setMap(paths, "/v1/fleet/templates/{id}:apply", pathItem("post", fleetOperation(
		"applyFleetTemplate",
		"Apply fleet template with bounded result custody",
		"Applies one stored fleet template to the local candidate with a revision guard and retains explicit per-peer result records. Peer rows are skipped or blocked; this does not perform peer RPC, production distributed execution, signed custody, HA fencing, traffic failover, or running-policy apply.",
		genericJSONBodyRef("ApplyFleetTemplateRequest", "#/definitions/openngfw.v1.ApplyFleetTemplateRequest"),
	)))
	setMap(paths, "/v1/fleet/template-results", pathItem("get", fleetOperation(
		"listFleetTemplateResults",
		"List fleet template apply results",
		"Lists server-retained local Fleet template apply result records for WebUI and CLI inspection. Records are unsigned local custody and not distributed peer attestation.",
		nil,
	)))
	setMap(paths, "/v1/fleet/templates/{id}:stage-candidate", pathItem("post", fleetOperation(
		"stageCandidateFleetTemplate",
		"Stage fleet template candidate",
		"Validates one stored local fleet template policy and stages it as the local candidate when expectedCandidateRevision matches. This does not apply running policy, fan out to peers, or retain distributed result custody.",
		genericJSONBodyRef("StageCandidateFleetTemplateRequest", "#/definitions/openngfw.v1.StageCandidateFleetTemplateRequest"),
	)))
	setMap(paths, "/v1/compliance/reports", mapping(
		"get", complianceOperation(
			"listComplianceReports",
			"List compliance reports",
			"Lists retained server-side compliance report records generated from audit, version, and log state.",
			nil,
			refSchema("#/definitions/openngfw.v1.ListComplianceReportsResponse"),
			[]*yaml.Node{integerParameter("limit", "query", false, "Maximum report summaries to return; the daemon clamps this to 100.")},
			false,
			false,
		),
		"post", complianceOperation(
			"createComplianceReport",
			"Create compliance report",
			"Generates and retains one server-side compliance report record for operator review/export.",
			genericJSONBodyRef("CreateComplianceReportRequest", "#/definitions/openngfw.v1.CreateComplianceReportRequest"),
			refSchema("#/definitions/openngfw.v1.CreateComplianceReportResponse"),
			nil,
			true,
			false,
		),
	))
	setMap(paths, "/v1/compliance/reports/{id}", pathItem("get", complianceOperation(
		"getComplianceReport",
		"Get compliance report",
		"Returns one retained compliance report record.",
		nil,
		refSchema("#/definitions/openngfw.v1.GetComplianceReportResponse"),
		[]*yaml.Node{complianceReportIDParameter()},
		false,
		false,
	)))
	setMap(paths, "/v1/compliance/reports/{id}/export", pathItem("get", complianceOperation(
		"exportComplianceReport",
		"Export compliance report",
		"Downloads one retained compliance report as a JSON artifact.",
		nil,
		nil,
		[]*yaml.Node{complianceReportIDParameter()},
		false,
		true,
	)))
	setMap(paths, "/v1/investigation/cases", mapping(
		"get", investigationOperation(
			"listInvestigationCases",
			"List investigation cases",
			"Lists audited server-retained investigation case summaries. Viewer role is sufficient for reads when management authentication is enabled.",
			nil,
			refSchema("#/definitions/openngfw.v1.ListInvestigationCasesResponse"),
			[]*yaml.Node{
				integerParameter("limit", "query", false, "Maximum cases to return; the daemon clamps this to its configured custody limit."),
				stringParameter("state", "query", false, "Optional case state filter: open, investigating, resolved, or closed."),
			},
			"200",
			nil,
		),
		"post", investigationOperation(
			"createInvestigationCase",
			"Create investigation case",
			"Stores one audited investigation case with sanitized packet and evidence payloads, then returns the retained case. The response includes a Location header pointing at /v1/investigation/cases/{id}. Operator role is required.",
			genericJSONBodyRef("CreateInvestigationCaseRequest", "#/definitions/openngfw.v1.CreateInvestigationCaseRequest"),
			refSchema("#/definitions/openngfw.v1.InvestigationCaseResponse"),
			nil,
			"201",
			nil,
		),
	))
	setMap(paths, "/v1/investigation/cases/{id}", mapping(
		"get", investigationOperation(
			"getInvestigationCase",
			"Get investigation case",
			"Returns one audited server-retained investigation case record by id.",
			nil,
			refSchema("#/definitions/openngfw.v1.InvestigationCaseResponse"),
			[]*yaml.Node{investigationCaseIDParameter()},
			"200",
			nil,
		),
		"patch", investigationOperation(
			"updateInvestigationCaseLifecycle",
			"Update investigation case lifecycle",
			"Updates bounded case lifecycle metadata such as title, state, and resolution note. Resolving or closing a case requires a non-empty resolution note. Operator role is required and audit failure rolls back the update.",
			genericJSONBodyRef("UpdateInvestigationCaseLifecycleRequest", "#/definitions/openngfw.v1.UpdateInvestigationCaseLifecycleRequest"),
			refSchema("#/definitions/openngfw.v1.InvestigationCaseResponse"),
			[]*yaml.Node{investigationCaseIDParameter()},
			"200",
			nil,
		),
	))
	setMap(paths, "/v1/investigation/cases/{id}/evidence", pathItem("post", investigationOperation(
		"addInvestigationCaseEvidence",
		"Add investigation case evidence",
		"Appends sanitized evidence items to one audited server-retained investigation case. Operator role is required and audit failure rolls back the append.",
		genericJSONBodyRef("AddInvestigationCaseEvidenceRequest", "#/definitions/openngfw.v1.AddInvestigationCaseEvidenceRequest"),
		refSchema("#/definitions/openngfw.v1.InvestigationCaseResponse"),
		[]*yaml.Node{investigationCaseIDParameter()},
		"200",
		map[string]string{"413": "Evidence limit exceeded"},
	)))
	setMap(paths, "/v1/system/automation/replay:validate", pathItem("post", automationReplayOperation(
		"validateAutomationReplay",
		"Validate automation replay runbook",
		"Normalizes browser-exported automation recordings, structured API steps, curl lines, and ngfwctl commands, then validates route safety, candidate revision binding, required acknowledgements, and optional dry-run/apply-authority execution planning without executing any step.",
		genericJSONBody("ValidateAutomationReplayRequest"),
	)))

	defs := ensureMap(root, "definitions")
	setMap(defs, "openngfw.v1.OIDCStatusResponse", oidcStatusDefinition())
	setMap(defs, "openngfw.v1.SAMLStatusResponse", samlStatusDefinition())
	setMap(defs, "openngfw.v1.CreateFleetTemplateRequest", createFleetTemplateRequestDefinition())
	setMap(defs, "openngfw.v1.ApplyPreviewFleetTemplateRequest", applyPreviewFleetTemplateRequestDefinition())
	setMap(defs, "openngfw.v1.ApplyPlanFleetTemplateRequest", applyPlanFleetTemplateRequestDefinition())
	setMap(defs, "openngfw.v1.ApplyFleetTemplateRequest", applyFleetTemplateRequestDefinition())
	setMap(defs, "openngfw.v1.StageCandidateFleetTemplateRequest", stageCandidateFleetTemplateRequestDefinition())
	setMap(defs, "openngfw.v1.FleetApplyPlanNodeInput", fleetApplyPlanNodeInputDefinition())
	setMap(defs, "openngfw.v1.ListComplianceReportsResponse", listComplianceReportsResponseDefinition())
	setMap(defs, "openngfw.v1.CreateComplianceReportResponse", complianceReportResponseDefinition())
	setMap(defs, "openngfw.v1.GetComplianceReportResponse", complianceReportResponseDefinition())
	setMap(defs, "openngfw.v1.ComplianceReportSummary", complianceReportSummaryDefinition())
	setMap(defs, "openngfw.v1.CreateComplianceReportRequest", createComplianceReportRequestDefinition())
	setMap(defs, "openngfw.v1.ComplianceErrorResponse", complianceErrorResponseDefinition())
	setMap(defs, "openngfw.v1.ListInvestigationCasesResponse", listInvestigationCasesResponseDefinition())
	setMap(defs, "openngfw.v1.InvestigationCaseResponse", investigationCaseResponseDefinition())
	setMap(defs, "openngfw.v1.InvestigationCaseRecord", investigationCaseRecordDefinition())
	setMap(defs, "openngfw.v1.InvestigationCaseSummary", investigationCaseSummaryDefinition())
	setMap(defs, "openngfw.v1.InvestigationEvidence", investigationEvidenceDefinition())
	setMap(defs, "openngfw.v1.InvestigationTargetSummary", investigationTargetSummaryDefinition())
	setMap(defs, "openngfw.v1.CreateInvestigationCaseRequest", createInvestigationCaseRequestDefinition())
	setMap(defs, "openngfw.v1.UpdateInvestigationCaseLifecycleRequest", updateInvestigationCaseLifecycleRequestDefinition())
	setMap(defs, "openngfw.v1.AddInvestigationCaseEvidenceRequest", addInvestigationCaseEvidenceRequestDefinition())
	setMap(defs, "openngfw.v1.InvestigationErrorResponse", investigationErrorResponseDefinition())

	var out bytes.Buffer
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		_ = enc.Close()
		return nil, fmt.Errorf("encode overlaid Swagger YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("close Swagger YAML encoder: %w", err)
	}
	return out.Bytes(), nil
}

func documentMap(doc *yaml.Node) (*yaml.Node, error) {
	if doc.Kind != yaml.DocumentNode || len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, errors.New("generated Swagger YAML root must be a mapping document")
	}
	return doc.Content[0], nil
}

func oidcStatusOperation() *yaml.Node {
	return mapping(
		"summary", scalar("Read browser OIDC status"),
		"operationId", scalar("getOIDCStatus"),
		"tags", sequence(scalar("auth")),
		"description", scalar("Reports browser SSO provider posture and, when a valid WebUI session cookie is present, the current actor, role, and CSRF token used by browser mutations."),
		"security", sequence(),
		"responses", mapping(
			"200", response("OIDC status", refSchema("#/definitions/openngfw.v1.OIDCStatusResponse")),
		),
	)
}

func samlStatusOperation() *yaml.Node {
	return mapping(
		"summary", scalar("Read browser SAML status"),
		"operationId", scalar("getSAMLStatus"),
		"tags", sequence(scalar("auth")),
		"description", scalar("Reports browser SAML provider posture and, when a valid WebUI session cookie is present, the current actor, role, and CSRF token used by browser mutations."),
		"security", sequence(),
		"responses", mapping(
			"200", response("SAML status", refSchema("#/definitions/openngfw.v1.SAMLStatusResponse")),
		),
	)
}

func redirectOperation(operationID, summary, description, failureDescription string, params []*yaml.Node) *yaml.Node {
	pairs := []any{
		"summary", scalar(summary),
		"operationId", scalar(operationID),
		"tags", sequence(scalar("auth")),
		"description", scalar(description),
		"security", sequence(),
	}
	if len(params) > 0 {
		pairs = append(pairs, "parameters", sequence(params...))
	}
	pairs = append(pairs, "responses", mapping(
		"302", mapping("description", scalar("Redirect")),
		"401", mapping("description", scalar(failureDescription)),
	))
	return mapping(pairs...)
}

func logoutOperation() *yaml.Node {
	return mapping(
		"summary", scalar("End browser SSO session"),
		"operationId", scalar("browserLogout"),
		"tags", sequence(scalar("auth")),
		"description", scalar("Clears the active WebUI session cookie. When a session cookie is present, unsafe-method CSRF protection requires the X-Phragma-CSRF header returned by the status endpoint."),
		"security", sequence(),
		"parameters", sequence(stringParameter("X-Phragma-CSRF", "header", false, "CSRF token returned by the OIDC or SAML status endpoint for browser-cookie mutations.")),
		"responses", mapping(
			"204", mapping("description", scalar("Session ended")),
			"403", mapping("description", scalar("Missing or invalid CSRF token")),
		),
	)
}

func fleetOperation(operationID, summary, description string, body *yaml.Node) *yaml.Node {
	pairs := []any{
		"summary", scalar(summary),
		"operationId", scalar(operationID),
		"tags", sequence(scalar("fleet")),
		"description", scalar(description),
		"responses", mapping(
			"200", mapping("description", scalar("OK")),
			"400", mapping("description", scalar("Validation failed")),
			"401", mapping("description", scalar("Unauthenticated")),
			"403", mapping("description", scalar("Forbidden")),
			"404", mapping("description", scalar("Not found")),
			"412", mapping("description", scalar("Precondition failed")),
			"500", mapping("description", scalar("Internal error")),
		),
	}
	if body != nil {
		pairs = append(pairs, "parameters", sequence(body))
	}
	return mapping(pairs...)
}

func fleetCreatedOperation(operationID, summary, description string, body *yaml.Node) *yaml.Node {
	pairs := []any{
		"summary", scalar(summary),
		"operationId", scalar(operationID),
		"tags", sequence(scalar("fleet")),
		"description", scalar(description),
		"responses", mapping(
			"201", mapping("description", scalar("Created")),
			"400", mapping("description", scalar("Validation failed")),
			"401", mapping("description", scalar("Unauthenticated")),
			"403", mapping("description", scalar("Forbidden")),
			"404", mapping("description", scalar("Not found")),
			"409", mapping("description", scalar("Conflict")),
			"412", mapping("description", scalar("Precondition failed")),
			"500", mapping("description", scalar("Internal error")),
		),
	}
	if body != nil {
		pairs = append(pairs, "parameters", sequence(body))
	}
	return mapping(pairs...)
}

func genericJSONBody(name string) *yaml.Node {
	return mapping(
		"name", scalar(name),
		"in", scalar("body"),
		"required", boolScalar(true),
		"schema", mapping("type", scalar("object")),
	)
}

func genericJSONBodyRef(name, ref string) *yaml.Node {
	return mapping(
		"name", scalar(name),
		"in", scalar("body"),
		"required", boolScalar(true),
		"schema", refSchema(ref),
	)
}

func complianceOperation(operationID, summary, description string, body, okSchema *yaml.Node, params []*yaml.Node, created, binary bool) *yaml.Node {
	responseNode := mapping("description", scalar("OK"))
	if okSchema != nil {
		responseNode = response("OK", okSchema)
	}
	if binary {
		responseNode = mapping(
			"description", scalar("Report JSON"),
			"headers", mapping(
				"Content-Disposition", typedProperty("string", "Attachment filename for the exported JSON report."),
				"X-Phragma-Payload-Sha256", typedProperty("string", "SHA-256 digest of the exported retained compliance report payload."),
				"ETag", typedProperty("string", "Strong entity tag derived from the exported payload SHA-256 digest."),
			),
			"schema", mapping("type", scalar("file")),
		)
	}
	responses := mapping(
		"200", responseNode,
		"400", response("Validation failed", refSchema("#/definitions/openngfw.v1.ComplianceErrorResponse")),
		"401", response("Unauthenticated", refSchema("#/definitions/openngfw.v1.ComplianceErrorResponse")),
		"403", response("Forbidden", refSchema("#/definitions/openngfw.v1.ComplianceErrorResponse")),
		"404", response("Not found", refSchema("#/definitions/openngfw.v1.ComplianceErrorResponse")),
		"405", response("Method not allowed", refSchema("#/definitions/openngfw.v1.ComplianceErrorResponse")),
		"500", response("Internal error", refSchema("#/definitions/openngfw.v1.ComplianceErrorResponse")),
	)
	if created {
		setMap(responses, "201", mapping(
			"description", scalar("Created"),
			"headers", mapping(
				"Location", typedProperty("string", "Path of the created retained compliance report."),
			),
			"schema", okSchema,
		))
		deleteMap(responses, "200")
	}
	pairs := []any{
		"summary", scalar(summary),
		"operationId", scalar(operationID),
		"tags", sequence(scalar("compliance")),
		"description", scalar(description),
		"responses", responses,
	}
	parameters := append([]*yaml.Node{}, params...)
	if body != nil {
		parameters = append(parameters, body)
	}
	if len(parameters) > 0 {
		pairs = append(pairs, "parameters", sequence(parameters...))
	}
	return mapping(pairs...)
}

func createFleetTemplateRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"required", sequence(scalar("name"), scalar("policy")),
		"properties", mapping(
			"name", typedProperty("string", "Operator-visible local Fleet template name."),
			"description", typedProperty("string", "Optional local Fleet template description."),
			"scope", typedProperty("string", "Optional operator-visible template scope label."),
			"labels", mapping("type", scalar("array"), "items", mapping("type", scalar("string"))),
			"policy", mapping("type", scalar("object"), "description", scalar("Policy packet JSON to retain as the local Fleet template source.")),
		),
	)
}

func applyPreviewFleetTemplateRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"expectedCandidateRevision", typedProperty("string", "Optional candidate revision guard used while previewing template impact."),
		),
	)
}

func applyPlanFleetTemplateRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"expectedCandidateRevision", typedProperty("string", "Optional candidate revision guard used while planning template apply."),
			"nodes", fleetApplyPlanNodesProperty("Operator-supplied bounded peer inventory rows used for apply planning."),
		),
	)
}

func applyFleetTemplateRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"required", sequence(scalar("expectedCandidateRevision"), scalar("comment")),
		"properties", mapping(
			"expectedCandidateRevision", typedProperty("string", "Required candidate revision guard for local candidate apply."),
			"comment", typedProperty("string", "Required operator change comment retained with the apply result."),
			"nodes", fleetApplyPlanNodesProperty("Operator-supplied bounded peer inventory rows retained as skipped or blocked result custody."),
		),
	)
}

func stageCandidateFleetTemplateRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"required", sequence(scalar("expectedCandidateRevision")),
		"properties", mapping(
			"expectedCandidateRevision", typedProperty("string", "Required candidate revision guard before staging this template."),
			"comment", typedProperty("string", "Optional operator change comment for the staged candidate."),
		),
	)
}

func fleetApplyPlanNodesProperty(description string) *yaml.Node {
	return mapping(
		"type", scalar("array"),
		"description", scalar(description),
		"maxItems", intScalar(32),
		"items", refSchema("#/definitions/openngfw.v1.FleetApplyPlanNodeInput"),
	)
}

func fleetApplyPlanNodeInputDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"id", typedProperty("string", "Operator-supplied node identifier."),
			"name", typedProperty("string", "Operator-supplied node name."),
			"role", typedProperty("string", "Operator-supplied node role."),
			"runtimeState", typedProperty("string", "Operator-supplied node runtime state."),
			"runningVersion", mapping("type", scalar("object"), "description", scalar("Operator-supplied running policy version context.")),
			"haState", typedProperty("string", "Operator-supplied HA state."),
			"haReady", typedProperty("boolean", "True when the supplied node is marked HA-ready."),
			"authoritative", typedProperty("boolean", "True when the supplied node row is authoritative for planning."),
			"detail", typedProperty("string", "Operator-supplied node detail string."),
		),
	)
}

func listComplianceReportsResponseDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"schemaVersion", typedProperty("string", "Response schema version."),
			"reports", mapping("type", scalar("array"), "items", refSchema("#/definitions/openngfw.v1.ComplianceReportSummary")),
		),
	)
}

func complianceReportResponseDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"schemaVersion", typedProperty("string", "Response schema version."),
			"report", refSchema("#/definitions/openngfw.v1.ComplianceReportSummary"),
		),
	)
}

func complianceReportSummaryDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"id", typedProperty("string", "Report id in report-YYYYMMDDTHHMMSSZ-xxxxxxxx form."),
			"schemaVersion", typedProperty("string", "Retained report record schema version."),
			"generatedAt", typedProperty("string", "Report generation timestamp."),
			"generatedBy", typedProperty("string", "Actor who generated the report."),
			"generatedByRole", typedProperty("string", "Role of the generating actor."),
			"authSource", typedProperty("string", "Authentication source for the generating actor."),
			"profile", typedProperty("string", "Normalized report profile."),
			"profileLabel", typedProperty("string", "Human-readable profile label."),
			"title", typedProperty("string", "Report title."),
			"source", typedProperty("string", "Report source, currently server-generated."),
			"unsigned", typedProperty("boolean", "True because signed custody is deferred hardening."),
			"signed", typedProperty("boolean", "False until production signing custody is implemented."),
			"serverStored", typedProperty("boolean", "True when the report is retained by the server."),
			"retentionEnforced", typedProperty("boolean", "False until production retention policy is enforced."),
			"auditEntryCount", typedProperty("integer", "Number of audit entries included in the report."),
			"versionCount", typedProperty("integer", "Number of policy versions included in the report."),
			"systemLogEntryCount", typedProperty("integer", "Number of system log entries included in the report."),
			"entryHashes", mapping("type", scalar("array"), "items", mapping("type", scalar("string"))),
			"latestAuditHash", typedProperty("string", "Latest audit hash seen while generating the report."),
			"filters", mapping("type", scalar("object"), "additionalProperties", mapping("type", scalar("string"))),
			"payloadSha256", typedProperty("string", "SHA-256 digest of the export payload."),
			"exportPath", typedProperty("string", "Browser/API export path for the retained JSON payload."),
		),
	)
}

func createComplianceReportRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"profile", typedProperty("string", "Report profile: operational, change-control, privileged-access, content-lifecycle, or incident-evidence."),
			"title", typedProperty("string", "Optional report title."),
			"auditLimit", typedProperty("integer", "Maximum audit entries to include."),
			"versionLimit", typedProperty("integer", "Maximum policy versions to include."),
			"logLimit", typedProperty("integer", "Maximum system log entries to include."),
			"actor", typedProperty("string", "Optional audit actor filter."),
			"action", typedProperty("string", "Optional audit action filter."),
			"version", typedProperty("string", "Optional policy version filter."),
			"since", typedProperty("string", "Optional RFC3339 lower time bound."),
			"until", typedProperty("string", "Optional RFC3339 upper time bound."),
			"query", typedProperty("string", "Optional audit detail search query."),
		),
	)
}

func complianceErrorResponseDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"error", mapping("type", scalar("object"), "properties", mapping(
				"code", typedProperty("string", "Stable error code."),
				"message", typedProperty("string", "Human-readable error message."),
			)),
		),
	)
}

func investigationOperation(operationID, summary, description string, body, okSchema *yaml.Node, params []*yaml.Node, successCode string, extraErrors map[string]string) *yaml.Node {
	if successCode == "" {
		successCode = "200"
	}
	successDescription := "OK"
	if successCode == "201" {
		successDescription = "Created"
	}
	successResponse := response(successDescription, okSchema)
	if successCode == "201" {
		successResponse = mapping(
			"description", scalar(successDescription),
			"headers", mapping(
				"Location", typedProperty("string", "Path of the created retained investigation case."),
			),
			"schema", okSchema,
		)
	}
	responses := mapping(
		successCode, successResponse,
		"400", response("Validation failed", refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")),
		"401", response("Unauthenticated", refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")),
		"403", response("Forbidden", refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")),
		"404", response("Not found", refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")),
		"405", response("Method not allowed", refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")),
	)
	for code, desc := range extraErrors {
		setMap(responses, code, response(desc, refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")))
	}
	setMap(responses, "500", response("Internal error", refSchema("#/definitions/openngfw.v1.InvestigationErrorResponse")))
	pairs := []any{
		"summary", scalar(summary),
		"operationId", scalar(operationID),
		"tags", sequence(scalar("investigation")),
		"description", scalar(description),
		"responses", responses,
	}
	parameters := append([]*yaml.Node{}, params...)
	if body != nil {
		parameters = append(parameters, body)
	}
	if len(parameters) > 0 {
		pairs = append(pairs, "parameters", sequence(parameters...))
	}
	return mapping(pairs...)
}

func automationReplayOperation(operationID, summary, description string, body *yaml.Node) *yaml.Node {
	pairs := []any{
		"summary", scalar(summary),
		"operationId", scalar(operationID),
		"tags", sequence(scalar("SystemService")),
		"description", scalar(description),
		"responses", mapping(
			"200", mapping("description", scalar("Validation report")),
			"400", mapping("description", scalar("Validation request was not valid JSON")),
			"401", mapping("description", scalar("Unauthenticated")),
			"403", mapping("description", scalar("Forbidden")),
			"405", mapping("description", scalar("Method not allowed")),
			"500", mapping("description", scalar("Internal error")),
		),
	}
	if body != nil {
		pairs = append(pairs, "parameters", sequence(body))
	}
	return mapping(pairs...)
}

func listInvestigationCasesResponseDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"schemaVersion", typedProperty("string", "Response schema version."),
			"cases", mapping("type", scalar("array"), "items", refSchema("#/definitions/openngfw.v1.InvestigationCaseSummary")),
			"hasMore", typedProperty("boolean", "True when additional matching cases exist beyond the returned limit."),
		),
	)
}

func investigationCaseResponseDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"schemaVersion", typedProperty("string", "Response schema version."),
			"case", refSchema("#/definitions/openngfw.v1.InvestigationCaseRecord"),
		),
	)
}

func investigationCaseRecordDefinition() *yaml.Node {
	props := investigationCaseMetadataProperties()
	setMap(props, "schemaVersion", typedProperty("string", "Record schema version."))
	setMap(props, "packet", mapping("type", scalar("object"), "description", scalar("Sanitized source investigation packet.")))
	setMap(props, "evidence", mapping("type", scalar("array"), "items", refSchema("#/definitions/openngfw.v1.InvestigationEvidence")))
	return mapping("type", scalar("object"), "properties", props)
}

func investigationCaseSummaryDefinition() *yaml.Node {
	return mapping("type", scalar("object"), "properties", investigationCaseMetadataProperties())
}

func investigationCaseMetadataProperties() *yaml.Node {
	return mapping(
		"id", typedProperty("string", "Case id in case-YYYYMMDDTHHMMSSZ-xxxxxxxx form."),
		"title", typedProperty("string", "Operator-visible case title."),
		"state", mapping("type", scalar("string"), "enum", sequence(scalar("open"), scalar("investigating"), scalar("resolved"), scalar("closed"))),
		"createdAt", typedProperty("string", "Creation timestamp."),
		"updatedAt", typedProperty("string", "Last update timestamp."),
		"resolutionNote", typedProperty("string", "Sanitized resolution note when present."),
		"resolvedAt", typedProperty("string", "Resolution or close timestamp when present."),
		"resolvedBy", typedProperty("string", "Actor who resolved or closed the case when present."),
		"createdBy", typedProperty("string", "Actor who created the case."),
		"createdByRole", typedProperty("string", "Role of the creating actor."),
		"authSource", typedProperty("string", "Authentication source for the creating actor."),
		"evidenceCount", typedProperty("integer", "Number of retained evidence items."),
		"summary", mapping("type", scalar("object"), "description", scalar("Sanitized case summary metadata.")),
	)
}

func investigationEvidenceDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"id", typedProperty("string", "Evidence id."),
			"addedAt", typedProperty("string", "Evidence append timestamp."),
			"addedBy", typedProperty("string", "Actor who appended this evidence."),
			"kind", typedProperty("string", "Evidence kind."),
			"title", typedProperty("string", "Evidence title."),
			"subjectId", typedProperty("string", "Optional evidence subject id."),
			"target", refSchema("#/definitions/openngfw.v1.InvestigationTargetSummary"),
			"payload", mapping("type", scalar("object"), "description", scalar("Sanitized original evidence payload.")),
		),
	)
}

func investigationTargetSummaryDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"kind", typedProperty("string", "Evidence target kind such as flow, alert, log, route, or report."),
			"key", typedProperty("string", "Bounded stable browser/server target key when available."),
			"route", typedProperty("string", "Redacted WebUI route for opening the evidence target when safe."),
			"routeRedacted", typedProperty("boolean", "True when unsafe route material was removed."),
			"source", typedProperty("string", "Target source such as traffic, threats, logs, compliance, or server-hydrated."),
			"title", typedProperty("string", "Bounded operator-visible target title."),
			"pinnedAt", typedProperty("string", "Original browser pin timestamp when provided."),
			"collectedAt", typedProperty("string", "Original evidence collection timestamp when provided."),
			"addedAt", typedProperty("string", "Server append timestamp for this target summary."),
		),
	)
}

func createInvestigationCaseRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"title", typedProperty("string", "Optional case title."),
			"packet", mapping("type", scalar("object"), "description", scalar("Browser-generated investigation case packet.")),
			"evidence", mapping("type", scalar("array"), "items", mapping("type", scalar("object"))),
		),
	)
}

func updateInvestigationCaseLifecycleRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"title", typedProperty("string", "Optional replacement title."),
			"state", mapping("type", scalar("string"), "enum", sequence(scalar("open"), scalar("investigating"), scalar("resolved"), scalar("closed"))),
			"resolutionNote", typedProperty("string", "Required when setting state to resolved or closed."),
		),
	)
}

func addInvestigationCaseEvidenceRequestDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"evidence", mapping("type", scalar("array"), "items", mapping("type", scalar("object"))),
		),
	)
}

func investigationErrorResponseDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"error", mapping("type", scalar("object"), "properties", mapping(
				"code", typedProperty("string", "Stable error code."),
				"message", typedProperty("string", "Human-readable error message."),
			)),
		),
	)
}

func samlStatusDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"enabled", typedProperty("boolean", "SAML browser SSO is configured."),
			"runtime_available", typedProperty("boolean", "SAML browser login/session runtime is active."),
			"idp_entity_id", typedProperty("string", "Configured SAML IdP entity ID."),
			"sp_entity_id", typedProperty("string", "Configured SAML SP entity ID."),
			"acs_url", typedProperty("string", "Configured SAML ACS URL."),
			"login_url", typedProperty("string", "Browser login endpoint."),
			"logout_url", typedProperty("string", "Browser logout endpoint."),
			"auth_source", typedProperty("string", "Authentication source for active browser sessions."),
			"authenticated", typedProperty("boolean", "True when the request has a valid browser session cookie."),
			"actor", typedProperty("string", "Authenticated actor name for the browser session."),
			"role", typedProperty("string", "Authenticated role for the browser session."),
			"csrf_token", typedProperty("string", "CSRF token required for browser-cookie mutation requests."),
		),
	)
}

func oidcStatusDefinition() *yaml.Node {
	return mapping(
		"type", scalar("object"),
		"properties", mapping(
			"enabled", typedProperty("boolean", "OIDC browser SSO is configured."),
			"issuer", typedProperty("string", "Configured OIDC issuer URL."),
			"client_id", typedProperty("string", "Configured OIDC client ID."),
			"login_url", typedProperty("string", "Browser login endpoint."),
			"logout_url", typedProperty("string", "Browser logout endpoint."),
			"auth_source", typedProperty("string", "Authentication source for active browser sessions."),
			"authenticated", typedProperty("boolean", "True when the request has a valid browser session cookie."),
			"actor", typedProperty("string", "Authenticated actor name for the browser session."),
			"role", typedProperty("string", "Authenticated role for the browser session."),
			"csrf_token", typedProperty("string", "CSRF token required for browser-cookie mutation requests."),
		),
	)
}

func stringParameter(name, in string, required bool, description string) *yaml.Node {
	return mapping(
		"name", scalar(name),
		"in", scalar(in),
		"required", boolScalar(required),
		"type", scalar("string"),
		"description", scalar(description),
	)
}

func integerParameter(name, in string, required bool, description string) *yaml.Node {
	return mapping(
		"name", scalar(name),
		"in", scalar(in),
		"required", boolScalar(required),
		"type", scalar("integer"),
		"format", scalar("int32"),
		"description", scalar(description),
	)
}

func investigationCaseIDParameter() *yaml.Node {
	return stringParameter("id", "path", true, "Investigation case id in case-YYYYMMDDTHHMMSSZ-xxxxxxxx form.")
}

func complianceReportIDParameter() *yaml.Node {
	return stringParameter("id", "path", true, "Compliance report id in report-YYYYMMDDTHHMMSSZ-xxxxxxxx form.")
}

func response(description string, schema *yaml.Node) *yaml.Node {
	return mapping("description", scalar(description), "schema", schema)
}

func refSchema(ref string) *yaml.Node {
	return mapping("$ref", scalar(ref))
}

func typedProperty(typ, description string) *yaml.Node {
	return mapping("type", scalar(typ), "description", scalar(description))
}

func ensureMap(parent *yaml.Node, key string) *yaml.Node {
	if node := getMap(parent, key); node != nil {
		if node.Kind == yaml.MappingNode {
			return node
		}
		node.Kind = yaml.MappingNode
		node.Tag = "!!map"
		node.Value = ""
		node.Content = nil
		return node
	}
	node := mapping()
	setMap(parent, key, node)
	return node
}

func getMap(parent *yaml.Node, key string) *yaml.Node {
	for i := 0; i+1 < len(parent.Content); i += 2 {
		if parent.Content[i].Value == key {
			return parent.Content[i+1]
		}
	}
	return nil
}

func setMap(parent *yaml.Node, key string, value *yaml.Node) {
	for i := 0; i+1 < len(parent.Content); i += 2 {
		if parent.Content[i].Value == key {
			parent.Content[i+1] = value
			return
		}
	}
	parent.Content = append(parent.Content, scalar(key), value)
}

func deleteMap(parent *yaml.Node, key string) {
	for i := 0; i+1 < len(parent.Content); i += 2 {
		if parent.Content[i].Value == key {
			parent.Content = append(parent.Content[:i], parent.Content[i+2:]...)
			return
		}
	}
}

func pathItem(method string, operation *yaml.Node) *yaml.Node {
	return mapping(method, operation)
}

func mapping(items ...any) *yaml.Node {
	node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	for i := 0; i+1 < len(items); i += 2 {
		key, ok := items[i].(string)
		if !ok {
			panic("mapping key must be string")
		}
		value, ok := items[i+1].(*yaml.Node)
		if !ok {
			panic("mapping value must be *yaml.Node")
		}
		node.Content = append(node.Content, scalar(key), value)
	}
	return node
}

func sequence(items ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq", Content: items}
}

func scalar(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

func boolScalar(value bool) *yaml.Node {
	if value {
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"}
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "false"}
}

func intScalar(value int) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.Itoa(value)}
}
